"""all models

Revision ID: cdf9fd3f4a28
Revises: 4feb0134b950
Create Date: 2025-04-15 23:31:25.850307

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = 'cdf9fd3f4a28'
down_revision = '4feb0134b950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('has_internal_menu', sa.Boolean(), nullable=False),
    sa.Column('external_app_link_pattern', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index('idx_stores_is_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_is_active'), ['is_active'], unique=False)

    op.create_table('menu_items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('store_id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_menu_items_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items'))
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index('idx_menuitems_is_available', ['is_available'], unique=False)
        batch_op.create_index('idx_menuitems_store_id', ['store_id'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=True),
    sa.Column('store_id', sa.GUID(length=16), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('apartment', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('entrance', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND store_id IS NULL) OR (user_id IS NULL AND store_id IS NOT NULL) OR (user_id IS NULL AND store_id IS NULL)', name=op.f('ck_addresses_chk_address_owner_type')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_addresses_store_id_stores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('idx_addresses_store_id', ['store_id'], unique=False)
        batch_op.create_index('idx_addresses_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('store_id', sa.GUID(length=16), nullable=False),
    sa.Column('delivery_address_id', sa.GUID(length=16), nullable=False),
    sa.Column('courier_id', sa.GUID(length=16), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['courier_users.id'], name=op.f('fk_orders_courier_id_courier_users')),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], name=op.f('fk_orders_delivery_address_id_addresses')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_orders_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_orders_courier_id', ['courier_id'], unique=False)
        batch_op.create_index('idx_orders_store_id', ['store_id'], unique=False)
        batch_op.create_index('idx_orders_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('order_id', sa.GUID(length=16), nullable=False),
    sa.Column('menu_item_id', sa.GUID(length=16), nullable=True),
    sa.Column('external_item_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_item', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_order_items_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('order_id', sa.GUID(length=16), nullable=False),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method_details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('order_id', name=op.f('uq_payments_order_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payments_gateway_transaction_id', ['gateway_transaction_id'], unique=False)
        batch_op.create_index('idx_payments_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_gateway_transaction_id'), ['gateway_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('order_id', sa.GUID(length=16), nullable=False),
    sa.Column('store_id', sa.GUID(length=16), nullable=True),
    sa.Column('courier_id', sa.GUID(length=16), nullable=True),
    sa.Column('menu_item_id', sa.GUID(length=16), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN store_id IS NOT NULL THEN 1 ELSE 0 END +  CASE WHEN courier_id IS NOT NULL THEN 1 ELSE 0 END +  CASE WHEN menu_item_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck_reviews_chk_review_target_single')),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_chk_review_rating_range')),
    sa.ForeignKeyConstraint(['courier_id'], ['courier_users.id'], name=op.f('fk_reviews_courier_id_courier_users')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_reviews_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_reviews_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_reviews_user_order', ['user_id', 'order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_courier_id'), ['courier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_menu_item_id'), ['menu_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Links a user to a specific permission.',
        existing_comment=None
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('role')

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Links a user to a specific permission.'
    )

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_store_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_order_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_menu_item_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_courier_id'))
        batch_op.drop_index('idx_reviews_user_order')

    op.drop_table('reviews')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_gateway_transaction_id'))
        batch_op.drop_index('idx_payments_status')
        batch_op.drop_index('idx_payments_gateway_transaction_id')

    op.drop_table('payments')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_store_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_courier_id'))
        batch_op.drop_index('idx_orders_user_id')
        batch_op.drop_index('idx_orders_store_id')
        batch_op.drop_index('idx_orders_courier_id')

    op.drop_table('orders')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_store_id'))
        batch_op.drop_index(batch_op.f('ix_addresses_postal_code'))
        batch_op.drop_index('idx_addresses_user_id')
        batch_op.drop_index('idx_addresses_store_id')

    op.drop_table('addresses')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index('idx_menuitems_store_id')
        batch_op.drop_index('idx_menuitems_is_available')

    op.drop_table('menu_items')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_is_active'))
        batch_op.drop_index('idx_stores_is_active')

    op.drop_table('stores')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
